version: '3'
services:
    api-gateway:
        build: ./api-gateway
        container_name: api-gateway
        ports:
            - "7000:5000"
        networks:
            - "flamingo-network"
    customer-service:
        build: ./customer-service
        container_name: customer-service
        networks:
            - "flamingo-network"
    customer-db:
        image: postgres
        container_name: customer-db
        environment:
            POSTGRES_PASSWORD: Abc.12345
            POSTGRES_DB: customer_db
        networks:
            - "flamingo-network"
        volumes:
            - ./customer-db/db-scripts:/docker-entrypoint-initdb.d
    order-service:
        build: ./order-service
        container_name: order-service
        networks:
            - "flamingo-network"
        environment:
            - PORT=80
    order-db:
        image: mongo
        container_name: order-db
        networks:
            - "flamingo-network"
    log-service:
        container_name: log-service
        build: ./log-service
        networks:
            - "flamingo-network"
    email-service:
        container_name: email-service
        build: ./email-service
        networks:
            - "flamingo-network"
    message-broker:
        image: rabbitmq:3-management
        container_name: message-broker
        hostname: message-broker
        environment:
            - RABBITMQ_DEFAULT_USER=user
            - RABBITMQ_DEFAULT_PASS=pass
            - RABBITMQ_VHOST=/
        networks:
            - "flamingo-network"
networks:
    flamingo-network:
        driver: bridge